# Generated by Django 5.1.1 on 2024-09-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0003_remove_event_description_remove_event_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
