# Generated by Django 5.1.1 on 2024-09-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0004_event_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.IntegerField(),
        ),
    ]
