# Generated by Django 5.1.1 on 2024-09-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0005_alter_event_end_time_alter_event_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='day_of_week',
            field=models.CharField(choices=[('ПОНЕДЕЛЬНИК', 'Понедельник'), ('ВТОРНИК', 'Вторник'), ('СРЕДА', 'Среда'), ('ЧЕТВЕРГ', 'Четверг'), ('ПЯТНИЦА', 'Пятница')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.CharField(max_length=200),
        ),
    ]
