# Generated by Django 5.1.1 on 2024-09-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0007_lesson_weekday_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='end_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='start_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='weekday',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
