# Generated by Django 5.1.1 on 2024-09-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0008_alter_lesson_end_time_alter_lesson_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='nomer',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
